name: CI/CD Deployment Pipeline
on:
  push:
    branches:
      - test
jobs:
  deploy:
    name: AWS CDK Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Project Version
        id: project_version
        run: echo "::set-output name=version::$(cat package.json | jq -r '.version')"

      - name: "Testing: Variables (env)"
        run:  env

      - name: "Testing: Variables (step)"
        run: echo ${{ steps.project_version.outputs.version }}
      