name: CI/CD Build Pipeline

on:
  push:
    branches-ignore:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  build:
    name: CI Build Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Dependencies
        run: npm ci --ignore-scripts
      - name: Linting
        run: npm run lint
      - name: Unit Testing
        run: npm run test
      - name: Transpile
        run: npm run compile
      - name: Synthesize
        run: npm run synth
      - name: Differences
        run: npm run diff
